## Numpy Library Exercises

In [1]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [3]:
import numpy as np

arr = np.random.randint(0, 11, 10)
print(f'Исходный массив: {arr}')

arr[(arr > 3) & (arr < 8)] = -arr[(arr > 3) & (arr < 8)]
print(f'Измененный массив: {arr}')

Исходный массив: [ 0  3 10 10  2  2  6 10  0  6]
Измененный массив: [ 0  3 10 10  2  2 -6 10  0 -6]


**2.** Replace the maximum element of a random array with 0

In [5]:
import numpy as np

arr = np.random.randint(0, 100, 10)
print(f'Исходный массив: {arr}')

max_index = np.argmax(arr)
arr[max_index] = 0
print(f'массив после замены максимума на 0: {arr}')

Исходный массив: [23 41 36  0 82 30 93 53 61 87]
массив после замены максимума на 0: [23 41 36  0 82 30  0 53 61 87]


**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [6]:
import numpy as np

a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

a_repeated = np.repeat(a, len(b), axis = 0)
b_repeated = np.tile(b, (len(a), 1))

result = np.hstack([a_repeated, b_repeated])
print(result)

[[1 2 5 6]
 [1 2 7 8]
 [3 4 5 6]
 [3 4 7 8]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [ ]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 3, 2],
    [4, 6, 5],
    [7, 8, 9],
    [2, 1, 3],
    [5, 4, 6],
    [9, 7, 8]
])

B = np.array([
    [1, 2],
    [4, 5]
])

B_sets = [set(row) for row in B] #превращаем строки B в множества для удобства проверки подмножеств {1, 2}, {4, 5}
mask = np.zeros(len(A), dtype=bool)

for i, row in enumerate(A):
    row_set = set(row)
    for b_set in B_sets:
        if b_set.issubset(row_set):
            mask[i] = True
            break
        
result = A[mask]
print('Строки А, которые содержат элементы из В:')
print(result)

Строки А, которые содержат элементы из В:
[[1 2 3]
 [4 5 6]
 [1 3 2]
 [4 6 5]
 [2 1 3]
 [5 4 6]]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [11]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 4, 4],
    [5, 5, 6],
    [7, 7, 7],
    [8, 9, 8],
    [1, 1, 1],
    [2, 2, 3],
    [3, 4, 5],
    [6, 6, 6],
    [7, 8, 9]
])

mask = []

for row in matrix:
    if len(np.unique(row)) > 1:
        mask.append(True)
    else:
        mask.append(False)

result = matrix[mask]
print(result)

[[1 2 3]
 [5 5 6]
 [8 9 8]
 [2 2 3]
 [3 4 5]
 [7 8 9]]


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [13]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6],
    [1, 1, 1],
    [7, 8, 9]
])

print("Исходная матрица:")
print(matrix)

unique_rows = np.unique(matrix, axis=0)

print("Матрица без повторяющихся строк:")
print(unique_rows)

Исходная матрица:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]
 [1 1 1]
 [7 8 9]]
Матрица без повторяющихся строк:
[[1 1 1]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [ ]:
def product_nonzero_diagonal_python(matrix):
    product = 1
    min_dim = min(len(matrix), len(matrix[0]))  
    
    for i in range(min_dim):
        elem = matrix[i][i]
        if elem != 0:
            product *= elem
    
    return product


X = [[1, 0, 1],
     [2, 0, 2],
     [3, 0, 3],
     [4, 4, 4]]

print(product_nonzero_diagonal_python(X)) 


3


In [15]:
import numpy as np

def product_nonzero_diagonal_numpy(matrix):
    diag = np.diag(matrix)
    
    nonzero_diag = diag[diag != 0]
  
    if nonzero_diag.size > 0:
        return np.prod(nonzero_diag)
    else:
        return 1  

X = np.array([[1, 0, 1],
              [2, 0, 2],
              [3, 0, 3],
              [4, 4, 4]])

print(product_nonzero_diagonal_numpy(X))  

3


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [16]:
def same_multiset_python(x, y):
    if len(x) != len(y):
        return False
    
    return sorted(x) == sorted(y)

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

print(same_multiset_python(x, y)) 

True


In [17]:
import numpy as np

def same_multiset_numpy(x, y):
    if len(x) != len(y):
        return False
    
    return np.array_equal(np.sort(x), np.sort(y))

x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

print(same_multiset_numpy(x, y)) 

True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [1]:
def max_preceded_by_zero_python(x):
    max_val = None
    
    for i in range(1, len(x)):
        if x[i-1] == 0: 
            if max_val is None or x[i] > max_val:
                max_val = x[i]
    
    return max_val

x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
print(max_preceded_by_zero_python(x))  

5


In [18]:
import numpy as np

def max_preceded_by_zero_numpy(x):
    mask = np.concatenate([[False], x[:-1] == 0])
    
    candidates = x[mask]
    
    if candidates.size > 0:
        return np.max(candidates)
    else:
        return None

x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max_preceded_by_zero_numpy(x)) 

5


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [19]:
def run_length_encoding_python(x):
    if not x:
        return [], []
    
    values = []
    counts = []
    
    current_val = x[0]
    current_count = 1
    
    for i in range(1, len(x)):
        if x[i] == current_val:
            current_count += 1
        else:
            values.append(current_val)
            counts.append(current_count)
            current_val = x[i]
            current_count = 1
    
    values.append(current_val)
    counts.append(current_count)
    
    return values, counts

x = [2, 2, 2, 3, 3, 3, 5]
values, counts = run_length_encoding_python(x)
print(values)  
print(counts) 

[2, 3, 5]
[3, 3, 1]


In [20]:
import numpy as np

def run_length_encoding_numpy(x):
    if len(x) == 0:
        return np.array([]), np.array([])
    
    changes = np.concatenate([[True], x[1:] != x[:-1]])
    
    values = x[changes]
    
    change_indices = np.concatenate([np.where(changes)[0], [len(x)]])
 
    counts = np.diff(change_indices)
    
    return values, counts

x = np.array([2, 2, 2, 3, 3, 3, 5])
values, counts = run_length_encoding_numpy(x)
print(values)  
print(counts) 

[2 3 5]
[3 3 1]


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [22]:
import math

def euclidean_distance_matrix_python(X, Y):
    result = []
    
    for x in X:
        row = []
        for y in Y:
            dist = math.sqrt(sum((a - b) ** 2 for a, b in zip(x, y)))
            row.append(dist)
        result.append(row)
    
    return result

X = [[1, 2], [3, 4], [5, 6]]
Y = [[1, 1], [2, 2]]

dist_matrix = euclidean_distance_matrix_python(X, Y)
for row in dist_matrix:
    print([round(val, 2) for val in row])

[1.0, 1.0]
[3.61, 2.24]
[6.4, 5.0]


In [21]:
import numpy as np

def euclidean_distance_matrix_numpy(X, Y):
    X_sq = np.sum(X**2, axis=1, keepdims=True)  
    Y_sq = np.sum(Y**2, axis=1)  
    
    dist_sq = X_sq - 2 * np.dot(X, Y.T) + Y_sq
  
    return np.sqrt(np.maximum(dist_sq, 0))  

X = np.array([[1, 2], [3, 4], [5, 6]])
Y = np.array([[1, 1], [2, 2]])

dist_matrix = euclidean_distance_matrix_numpy(X, Y)
print(dist_matrix)

[[1.         1.        ]
 [3.60555128 2.23606798]
 [6.40312424 5.        ]]


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [77]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [170]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [1]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

average_calories = np.mean(calorie_stats)

difference = average_calories - 60

print(f"Средняя калорийность конкурентов: {average_calories:.2f}")
print(f"Наша крупа (60 калорий) ниже среднего на: {difference:.2f} калорий")
print(f"Это в {average_calories / 60:.2f} раз больше, чем наша крупа")

Средняя калорийность конкурентов: 106.88
Наша крупа (60 калорий) ниже среднего на: 46.88 калорий
Это в 1.78 раз больше, чем наша крупа


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [2]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

calorie_stats_sorted = np.sort(calorie_stats)

print("Отсортированные данные:")
print(calorie_stats_sorted)

Отсортированные данные:
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [3]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

median_calories = np.median(calorie_stats)

mean_calories = np.mean(calorie_stats)

print(f"Среднее значение (mean): {mean_calories:.2f}")
print(f"Медиана (median): {median_calories:.2f}")

if mean_calories > median_calories:
    print("Среднее выше медианы → распределение скошено вправо")
elif mean_calories < median_calories:
    print("Среднее ниже медианы → распределение скошено влево")
else:
    print("Среднее равно медиане → распределение симметричное")

Среднее значение (mean): 106.88
Медиана (median): 110.00
Среднее ниже медианы → распределение скошено влево


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [4]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

percentiles = np.arange(0, 101, 5)  

nth_percentile = None

for p in percentiles:
    value = np.percentile(calorie_stats, p)
    print(f"Перцентиль {p}%: {value:.1f} калорий")
    
    if value > 60:
        nth_percentile = p
        break

print(f"\nСамый низкий перцентиль, превышающий 60 калорий: {nth_percentile}%")
print(f"Значение: {np.percentile(calorie_stats, nth_percentile):.1f} калорий")

Перцентиль 0%: 50.0 калорий
Перцентиль 5%: 70.0 калорий

Самый низкий перцентиль, превышающий 60 калорий: 5%
Значение: 70.0 калорий


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [5]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

above_60 = np.sum(calorie_stats > 60)

total = len(calorie_stats)

more_calories = (above_60 / total) * 100

print(f"Всего продуктов: {total}")
print(f"Продуктов с калорийностью > 60: {above_60}")
print(f"Процент продуктов с калорийностью > 60: {more_calories:.1f}%")

Всего продуктов: 77
Продуктов с калорийностью > 60: 74
Процент продуктов с калорийностью > 60: 96.1%


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [6]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

calorie_std = np.std(calorie_stats)

print(f"Стандартное отклонение: {calorie_std:.2f} калорий")
print(f"Среднее значение: {np.mean(calorie_stats):.2f} калорий")

Стандартное отклонение: 19.36 калорий
Среднее значение: 106.88 калорий


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [8]:
import numpy as np

calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")

mean_calories = np.mean(calorie_stats)
median_calories = np.median(calorie_stats)
std_calories = np.std(calorie_stats)
more_calories = np.mean(calorie_stats > 60) * 100
our_cereal = 60

print("Анализ калорийности конкурентов:")
print(f"Среднее: {mean_calories:.1f} калорий")
print(f"Медиана: {median_calories:.1f} калорий")
print(f"Стандартное отклонение: {std_calories:.1f} калорий")
print(f"Процент продуктов с калорийностью > 60: {more_calories:.1f}%")

print("\nМаркетинговый вывод для Mycrunch:")
print(f"CrunchieMunchies содержит {our_cereal} калорий на порцию,")
print(f"что на {mean_calories - our_cereal:.1f} калорий ниже среднего показателя конкурентов.")
print(f"Более того, {more_calories:.1f}% конкурентов имеют более высокую калорийность.")
print(f"Это делает CrunchieMunchies идеальным выбором для потребителей,")
print("которые ищут здоровый и низкокалорийный завтрак.")

Анализ калорийности конкурентов:
Среднее: 106.9 калорий
Медиана: 110.0 калорий
Стандартное отклонение: 19.4 калорий
Процент продуктов с калорийностью > 60: 96.1%

Маркетинговый вывод для Mycrunch:
CrunchieMunchies содержит 60 калорий на порцию,
что на 46.9 калорий ниже среднего показателя конкурентов.
Более того, 96.1% конкурентов имеют более высокую калорийность.
Это делает CrunchieMunchies идеальным выбором для потребителей,
которые ищут здоровый и низкокалорийный завтрак.
